info='''Pellentesque scelerisque turpis sit amet massa ullamcorper, a sagittis felis tincidunt. Sed sit amet justo sit amet sem cursus gravida sed sed orci. Suspendisse ut lacus orci. Aliquam eu urna nec dolor convallis ultricies nec nec tortor. Quisque luctus aliquet nisi et volutpat. Duis maximus lectus urna, sed commodo augue porta suscipit. Aliquam sed magna dolor. Donec eget urna in orci viverra facilisis et ac odio. Vestibulum tincidunt urna metus, et ultrices elit ornare ac. Praesent et justo eros. In ullamcorper eget tellus vitae tempor. Vestibulum ut ex in purus imperdiet mollis. Phasellus augue velit, fringilla eu elit ut, vulputate tincidunt augue. Nullam varius bibendum augue in ultricies. Praesent pharetra lobortis imperdiet. Sed egestas arcu in purus dapibus, sit amet.'''

what='''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris hendrerit at dolor eu molestie. Aliquam condimentum ante at facilisis iaculis. Quisque aliquam bibendum pellentesque. Morbi gravida quam purus, eu tincidunt massa tristique volutpat. Ut lobortis, erat sed blandit convallis, quam justo sollicitudin elit, eu egestas mi velit eget nunc. Ut mollis nulla sit amet leo commodo, eleifend vulputate augue facilisis. Quisque lobortis velit in posuere finibus. Nam maximus ipsum turpis. Morbi ex nunc, blandit sit amet elementum ut, rutrum et ipsum. Vivamus elementum, massa feugiat consectetur mollis, enim massa pharetra nibh, et ornare mauris turpis sit amet massa. Donec luctus lacus non lectus rutrum, id varius felis finibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla iaculis posuere enim, ut accumsan arcu aliquam at. Nunc efficitur risus ac eros finibus ultrices.

Integer varius eros non neque pharetra, nec efficitur turpis laoreet. Mauris vitae dignissim metus, at iaculis sapien. Sed sed sagittis est. Phasellus tincidunt ut sapien quis finibus. Aliquam eu sapien tortor. Etiam sed ultrices erat. Suspendisse et ultrices nibh, quis dignissim eros. Proin porta, ante sed iaculis congue, nisi arcu eleifend felis, id dignissim diam neque at massa. Sed augue mi, fermentum nec ex at, euismod congue orci. Mauris eleifend nunc ac enim condimentum, id convallis enim elementum. Sed ut ante blandit, semper dui et, lacinia orci.

Vivamus porta diam quis tempor pellentesque. Integer vitae lacus in ligula volutpat consequat. Etiam lobortis eget nisl et fringilla. Suspendisse venenatis enim a felis finibus rhoncus. Nulla purus justo, rutrum vitae nulla vel, semper ullamcorper dolor. Suspendisse aliquet leo quis diam vehicula, vitae elementum neque tristique. Aliquam erat volutpat. Aliquam congue nunc id felis lobortis, ac vestibulum lorem faucibus. Morbi malesuada lorem sit amet eros fringilla semper. Etiam ultrices pharetra massa dignissim maximus. Mauris sem orci, feugiat quis erat in, lobortis condimentum nisl. Phasellus nec rutrum ante. Proin varius felis facilisis eros bibendum, vel facilisis ligula feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus vel arcu in tortor tristique dictum non eleifend lorem.

Ut accumsan blandit mauris eget sollicitudin. Phasellus ligula risus, venenatis quis est elementum, hendrerit tincidunt velit. Nulla facilisi. Duis molestie elementum felis, eu lobortis tortor volutpat quis. Nunc neque libero, tristique sed sapien in, tincidunt tempus turpis. Nam faucibus tempor lectus, at maximus sem. Vestibulum vitae dolor vel enim porta congue eget et massa. Fusce a nisl augue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse purus velit, feugiat in consectetur at, placerat quis ligula.

Nunc porta libero ac sollicitudin pulvinar. Cras sed sollicitudin justo, ac vulputate sapien. Phasellus eleifend felis ac dui ullamcorper vestibulum. Sed sed congue ante, nec venenatis eros. Donec commodo aliquam magna nec pulvinar. Integer congue quam quis eleifend fermentum. Donec dignissim dignissim molestie.

Nunc faucibus nulla vitae neque tempus, vitae commodo ipsum tempus. Sed at rutrum erat. Ut commodo, nisi vitae finibus elementum, quam massa sollicitudin mi, quis ullamcorper eros dui in ligula. Nulla dapibus tincidunt urna faucibus lacinia. Vestibulum accumsan consectetur sollicitudin. Nam elementum ligula mauris, nec cursus dui pharetra nec. Aliquam erat volutpat. Duis vulputate blandit ligula, eu luctus nunc pulvinar eu. Pellentesque mattis sodales sapien, at porta metus auctor vel. Phasellus congue nisi eget augue porta aliquam. Morbi ornare ipsum pellentesque pellentesque tincidunt. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Morbi non massa nec leo pellentesque lacinia. Nullam fermentum massa ac massa vulputate consectetur. Proin suscipit nec nisi eu pellentesque. Proin volutpat, metus quis viverra dictum, erat neque faucibus nibh, id aliquet velit justo eu risus. Cras accumsan id arcu quis efficitur. Etiam imperdiet, tortor vel vulputate pulvinar, nisl eros condimentum justo, eget pretium tellus lorem euismod erat. Suspendisse fringilla facilisis tellus eu malesuada. Nullam tristique pulvinar ante, porttitor dignissim magna accumsan in. Quisque velit quam, sodales nec augue sed, rhoncus lacinia elit. Nunc in sapien sed eros aliquet fermentum nec vel dolor. Nunc iaculis nibh et urna hendrerit, non mollis erat vehicula. Cras vel hendrerit tellus. Nunc eget libero in sem tempus rutrum sed ullamcorper nulla.

Maecenas eu enim nunc. Curabitur vestibulum consequat ex. Aliquam in tincidunt velit. Morbi faucibus lacus et aliquet sollicitudin. Cras interdum commodo mi vitae vehicula. Sed pellentesque sagittis maximus. Quisque lobortis ac lorem vitae fermentum. Cras facilisis urna et ante ultrices tincidunt. Cras dignissim.'''


to_do='''Fusce ut sagittis turpis. Praesent lacinia sed mauris et elementum. Suspendisse non consequat quam, vitae lobortis ex. Sed molestie congue turpis nec pellentesque. Ut odio enim, egestas quis quam hendrerit, vestibulum pellentesque augue. Nam malesuada feugiat magna ac molestie. Morbi at metus sit amet arcu malesuada dapibus. Quisque felis est, porta laoreet dolor sed, venenatis vehicula dui. Nulla tempor pharetra lacus, eget ultrices mi suscipit ultrices. Ut at ornare orci. Quisque tempus elementum mauris vitae lobortis. Phasellus elementum velit velit, vel scelerisque lacus convallis sed. Aliquam ultricies dolor vestibulum tincidunt porttitor. Maecenas rutrum ipsum ut finibus commodo. Curabitur luctus et nibh sit amet faucibus. Aenean eget ullamcorper ante. Aliquam porta lectus massa, quis consectetur diam tincidunt eget. Nulla fringilla laoreet.'''


some='''
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam lobortis ultricies vulputate. Mauris aliquet varius hendrerit. Praesent tempus tempus mauris sit amet blandit. Nullam in dignissim ipsum, ac hendrerit magna. Aenean magna nulla, molestie eget nibh sed, finibus varius nibh. Integer imperdiet tortor et imperdiet ullamcorper. Aliquam viverra sapien urna, eget cursus magna congue in. Pellentesque id neque sed metus rutrum condimentum. Quisque eu nisi eget ipsum fermentum aliquet. Ut imperdiet quam nulla, ac sollicitudin lectus posuere quis. Integer lorem mi, rutrum id erat a, tempor congue ligula. Aenean molestie vitae leo eu accumsan. Morbi at eleifend magna. Aliquam mollis ipsum vitae laoreet ullamcorper. Nulla elementum, tellus in tincidunt finibus, leo magna ullamcorper libero, ac fringilla elit velit a urna.

Aliquam ultricies purus arcu, sit amet dignissim massa vulputate non. Nam et turpis quis neque sagittis pharetra at et quam. Praesent sit amet dictum metus. In scelerisque tempor dignissim. Duis felis dui, lacinia a tellus at, porttitor scelerisque sapien. Vestibulum et est ac ligula commodo ultrices. Nunc risus libero, faucibus eget leo eu, viverra tempor eros. Aliquam ut venenatis magna. Praesent ut risus eu urna malesuada consectetur ac et purus. Nulla erat dolor, blandit nec leo sit amet, faucibus dapibus tortor. Sed eleifend elit sed dolor venenatis elementum. Phasellus eu ultrices quam. Vivamus luctus hendrerit purus eu hendrerit. Fusce tempus nec purus non convallis.

Maecenas scelerisque ex leo, nec tempus justo gravida nec. Ut nec quam purus. Proin id ipsum vel massa pretium vehicula. Vivamus laoreet nisl in velit aliquet, eget pharetra nisi dignissim. Proin auctor tortor a eros sollicitudin semper. Praesent nec luctus arcu. Suspendisse sed magna a eros placerat bibendum a sit amet metus.

Aliquam erat volutpat. Suspendisse nec pulvinar tellus. Proin condimentum libero sed dui rhoncus scelerisque. Proin at vestibulum libero. Suspendisse ut arcu eget augue dignissim scelerisque quis a turpis. Nam odio mauris, efficitur eu accumsan eu, imperdiet ut leo. In eu mi ac enim bibendum congue non ac magna. Maecenas quis nulla ante. Curabitur semper sapien sit amet finibus tincidunt. Vestibulum eu elit sed quam ultricies varius. Morbi ac tempor nunc. Maecenas iaculis nunc vel orci gravida molestie. Curabitur eget sapien congue, pharetra tellus nec, vestibulum libero. Proin consequat accumsan nisi. Nulla non enim et ligula porttitor hendrerit sit amet ut magna.

Cras efficitur ullamcorper arcu, non suscipit nisl tristique et. Maecenas pulvinar felis libero, ac mollis mi consectetur sollicitudin. In vitae lacus iaculis turpis imperdiet iaculis. Etiam sit amet rhoncus lacus. Nam scelerisque vehicula eros et tincidunt. Nulla malesuada libero magna, eget euismod magna imperdiet id. Sed quis odio non ante semper malesuada.'''